### ISSUE TITLE
the support of amp-script

### ISSUE THREAD

**Issue by jennyrenjiale** [dfrankland/ampreact#7]
awesome works~! here is one thing i want to make sure....can i use amp-script here ?

**Comment by dfrankland** [comment]
Could you explain a bit more? `react-amphtml` has a component which automatically generates amp-script tags via context, example here:
https://github.com/dfrankland/ampreact/blob/56f44a1eb778b01b3cf556545f47e813c0858906/pages/_document.tsx#L83

You can of course add script tags manually if you’d like as well to the head of the page:
https://github.com/dfrankland/ampreact/blob/56f44a1eb778b01b3cf556545f47e813c0858906/pages/_document.tsx#L97-L102

`react-amphtml` also provides a convenience `<Script />` component as well:
https://github.com/dfrankland/react-amphtml/blob/10d3343a66a75665ba46fde2003fde0e4f902aaa/src/amphtml/components/Script.tsx

**Comment by jennyrenjiale** [comment]
> Could you explain a bit more? `react-amphtml` has a component which automatically generates amp-script tags via context, example here:
> https://github.com/dfrankland/ampreact/blob/56f44a1eb778b01b3cf556545f47e813c0858906/pages/_document.tsx#L83
> 
> You can of course add script tags manually if you’d like as well to the head of the page:
> https://github.com/dfrankland/ampreact/blob/56f44a1eb778b01b3cf556545f47e813c0858906/pages/_document.tsx#L97-L102
> 
> `react-amphtml` also provides a convenience `<Script />` component as well:
> https://github.com/dfrankland/react-amphtml/blob/10d3343a66a75665ba46fde2003fde0e4f902aaa/src/amphtml/components/Script.tsx

ok i have tried, it can work ! i thought amp-script component has just released recently therefore you may not support that.
