### ISSUE TITLE
After implement ampreact from your example app don't refresh itself after file changing!

### ISSUE THREAD

**Issue by narek1993x** [dfrankland/ampreact#8]

**Comment by narek1993x** [comment]
I also use in my app server!

**Comment by dfrankland** [comment]
Do you mean that the page on the browser doesn't refresh after changing some code?

**Comment by narek1993x** [comment]
Yes, you can try on your own boilerplate!

**Comment by dfrankland** [comment]
AMPHTML doesn't support arbitrary JavaScript, so adding hot-reloading or reloading is not valid. Because of that ampreact is server-side only. It is possible to add reloading though using something like browser sync, but it should only be done for development since it will be invalid AMPHTML.

**Comment by narek1993x** [comment]
Thank you
