### ISSUE TITLE
The support of application/ld+json in head file

### ISSUE THREAD

**Issue by narek1993x** [dfrankland/ampreact#9]
When i write application/ld+json script for search engines our html don't have clue about it.
Why?

```javascript
import Head from 'next/head';

<Head>
   <script type="application/ld+json">
          {{
            '@context': 'http://schema.org',
            '@type': 'NewsArticle',
            mainEntityOfPage: `${product.host}/index/index.html`,
            headline,
            datePublished,
            dateModified,
            description,
            author: {
              '@type': 'Person',
              name: authorName
            },
            publisher: {
              '@type': 'Organization',
              name: 'Test',
              logo: {
                '@type': 'ImageObject',
                url: getImageUrl('static/imgs/assets/Header/logo-green.png'),
                width: 350,
                height: 135
              }
            },
            image: {
              '@type': 'ImageObject',
              url: getImageUrl(imageUrl),
              height: 480,
              width: 412
            }
          }}
   </script>
</Head>
```

**Comment by dfrankland** [comment]
I don't think this is a problem with `ampreact`, so much as React itself. To set things like objects as children of `<script />` you have to use [`dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml).

I recommend taking a look at how the Next.js examples do JSON-LD:
https://github.com/zeit/next.js/blob/b8c9a1b/examples/with-next-seo/pages/jsonld.js

**Comment by narek1993x** [comment]
Thank you Dylan i already solved it with "dangerouslySetInnerHTML".
And i pass head from props in our head tag to get meta tags and other stuff from next/head, also i maped and pass null each of head item because it's not work in other way.

```javascript
const head = (initialProps.head || []).map(item => {
        // don't pass urf-8 because it's duplicated
        if (item.props.charSet && item.props.charSet === 'utf-8') return; 
        return { ...item, key: null };
});

return {
        ...initialProps,
        head,
        title,
        url: ctx.asPath || '',
        ampScriptTags: ampScripts.getScriptElements(),
        ampStyleTag
};
```
About next-seo i didn't know thank you one more time.
One more question is there any reason in _document.js you didn't pass head from props in to head tag?

```javascript
 <Amp.Html format="amp" lang="en">
   <head>
      {headerBoilerplate(url)}
      {head} // in my app i use head in this order
      {title}      
      {ampScriptTags}
      {ampStyleTag}
    </head>
   <body dangerouslySetInnerHTML={{ __html: html }} />
</Amp.Html>
```

**Comment by dfrankland** [comment]
AMP HTML pages are pretty locked down, so I set this up to only explicitly include the items needed. I think it would be a nice idea to filter through the head elements and find any JSON-LD scripts to inject.

**Comment by narek1993x** [comment]
Anyways thank you.
